version: "3"

services:
  app:
    image: ghcr.io/${GITHUB_REPO_LOWER}/smartdine_laravel:${IMAGE_TAG:-latest}
    container_name: smartdine_app_${IMAGE_TAG:-latest}
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=smartdine_${IMAGE_TAG:-latest}
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD:-secretpassword}
      - APP_ENV=${IMAGE_TAG:-production}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-default_key}
    restart: always
    depends_on:
      - database
      - redis

  database:
    image: mysql:8.0
    container_name: smartdine_db_${IMAGE_TAG:-latest}
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secretpassword}
      - MYSQL_DATABASE=smartdine_${IMAGE_TAG:-latest}
    volumes:
      - smartdine_db:/var/lib/mysql
    restart: always

  redis:
    image: redis:alpine
    container_name: smartdine_redis_${IMAGE_TAG:-latest}
    ports:
      - "6379:6379"
    volumes:
      - smartdine_redis:/data
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: smartdine_phpmyadmin_${IMAGE_TAG:-latest}
    environment:
      - PMA_HOST=database
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secretpassword}
    ports:
      - "8080:80"
    depends_on:
      - database
    restart: always

  ws-server:
    image: ghcr.io/${GITHUB_REPO_LOWER}/smartdine_ws:${IMAGE_TAG:-latest}
    container_name: smartdine_ws_${IMAGE_TAG:-latest}
    ports:
      - "3000:3000"
    depends_on:
      - app
    restart: always

volumes:
  smartdine_db:
    name: smartdine_db_${IMAGE_TAG:-latest}
  smartdine_redis:
    name: smartdine_redis_${IMAGE_TAG:-latest}
