services:
  app:
    image: yehiaarja/dockersmartdine:latest
    container_name: smartdine_app
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=smartdine
      - DB_USERNAME=root
      - DB_PASSWORD=secretpassword
      - APP_ENV=production
      - OPENAI_API_KEY=default_key
    restart: always
    depends_on:
      - database
      - redis

  database:
    image: mysql:8.0
    container_name: smartdine_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secretpassword
      - MYSQL_DATABASE=smartdine
    volumes:
      - smartdine_db:/var/lib/mysql
    restart: always

  redis:
    image: redis:alpine
    container_name: smartdine_redis
    ports:
      - "6379:6379"
    volumes:
      - smartdine_redis:/data
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: smartdine_phpmyadmin
    environment:
      - PMA_HOST=database
      - MYSQL_ROOT_PASSWORD=secretpassword
    ports:
      - "8080:80"
    depends_on:
      - database
    restart: always

  ws-server:
    image: yehiaarja/dockersmartdine-ws:latest
    container_name: smartdine_ws
    ports:
      - "3000:3000"
    depends_on:
      - app
    restart: always

volumes:
  smartdine_db:
  smartdine_redis:
