version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8015:8000
    depends_on:
      - mysql_db
      - redis_cache
    volumes:
      - .:/app
    command: php artisan serve --host=0.0.0.0 --port=8000
    restart: always

  mysql_db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=restaurant_db
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_pass
      - MYSQL_ROOT_HOST=%
    ports:
      - 3399:3306
    volumes:
      - db-data:/var/lib/mysql

  redis_cache:
    image: redis:7-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis-data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql_db
      - PMA_USER=laravel_user
      - PMA_PASSWORD=laravel_pass
    ports:
      - 8082:80
    depends_on:
      - mysql_db

volumes:
  db-data:
  redis-data:
