version: '3.8'
services:

  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=restaurant_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '33060:3306'

  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - '63790:6379'

  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    depends_on:
      - database
      - redis
    environment:
      APP_ENV: production
      APP_DEBUG: 'true'
      APP_KEY: ${APP_KEY}
      APP_URL: http://localhost
      APP_PORT: 8000

      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: restaurant_db
      DB_USERNAME: root
      DB_PASSWORD: 1234

      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./:/app:cached
      - storage_logs:/app/storage/logs
      - storage_cache:/app/bootstrap/cache
    ports:
      - '8000:8000'
    command: php artisan serve --host=0.0.0.0 --port=8000

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 1234
    ports:
      - '8080:80'

volumes:
  db_data:
  redis_data:
  storage_logs:
  storage_cache:
