version: '3.8'

services:
  laravel:
    image: bitnami/laravel:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:cached
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_pass
      - DB_DATABASE=restaurant_db
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=restaurant_db
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_pass
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root

volumes:
  mysql_data:
