version: '3.8'

services:
  server:
    image: yehiaarja/dockersmartdine:latest
    environment:
      - LARAVEL_DATABASE_HOST=database
      - LARAVEL_DATABASE_NAME=restaurant_db
      - LARAVEL_DATABASE_USER=root
      - LARAVEL_DATABASE_PASSWORD=1234
      - LARAVEL_DATABASE_PORT_NUMBER=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
    restart: always
    ports:
      - 80:8000
    depends_on:
      - database
      - redis
    command: /app/shellScript.sh

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=restaurant_db
    ports:
      - 3380:3306
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=database
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 8080:80
    depends_on:
      - database

volumes:
  db-data:
  redis-data: