version: "3.8"

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # mount your code and host-installed vendor into /app
    volumes:
      - ./:/app:cached
      - ./vendor:/app/vendor:delegated
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_pass
      DB_DATABASE: restaurant_db
      CACHE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"
    volumes:
      - ./:/app:cached
      - ./vendor:/app/vendor:delegated
    depends_on:
      - laravel
      - mysql
      - redis

volumes:
  mysql_data:
