name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - production

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build via docker compose
        run: docker compose -f smartDine-server/docker-compose.yml build --pull --progress=plain

  test:
    name: Run Laravel Tests
    runs-on: ubuntu-latest
    needs: build

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, pdo, pdo_mysql, zip

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: smartDine-server/vendor
          key: composer-${{ hashFiles('smartDine-server/composer.lock') }}
          restore-keys: composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --no-interaction
        working-directory: smartDine-server

      - name: Copy environment file
        run: cp smartDine-server/.env.example smartDine-server/.env
        working-directory: smartDine-server

      - name: Generate APP_KEY
        run: php artisan key:generate --ansi
        working-directory: smartDine-server

      - name: Run migrations
        run: php artisan migrate --force --no-interaction
        working-directory: smartDine-server

      - name: Run PHPUnit
        run: php artisan test --no-interaction --verbose
        working-directory: smartDine-server

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: test
    if: |
      github.ref == 'refs/heads/main' ||
      github.ref == 'refs/heads/production'
    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      BRANCH: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_DEPLOY_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@"${EC2_HOST}" << 'EOF'
            cd ~/Restaurant-Manager/smartDine-server
            git pull origin "${BRANCH}"
            docker compose down
            docker compose up -d --build
          EOF
