name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - production

env:
  DOCKER_COMPOSE_VERSION: "3.8"

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Verify Docker Compose Installation
        run: docker-compose --version

      - name: Build containers
        working-directory: smartDine-server
        run: docker-compose -f docker-compose.yml build

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, json, tokenizer, bcmath, redis, pdo_mysql

      - name: Install dependencies
        working-directory: smartDine-server
        run: composer install --no-interaction --prefer-dist

      - name: Configure environment
        working-directory: smartDine-server
        run: |
          cp .env.example .env
          echo "APP_ENV=testing" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_DATABASE=test_db" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env

      - name: Run tests
        working-directory: smartDine-server
        run: |
          php artisan key:generate --env=testing
          php artisan migrate:fresh --env=testing
          php artisan test

  deploy:
    name: Deploy
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set deployment variables
        id: set-vars
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "server=${{ secrets.STAGING_SERVER }}" >> $GITHUB_OUTPUT
            echo "envfile=.env.staging" >> $GITHUB_OUTPUT
            echo "pkey=${{ secrets.SSH_STAGING_PRIVATE_KEY }}" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == "refs/heads/production" ]]; then
            echo "server=${{ secrets.PRODUCTION_SERVER }}" >> $GITHUB_OUTPUT
            echo "envfile=.env.production" >> $GITHUB_OUTPUT
            echo "pkey=${{ secrets.SSH_PRODUCTION_PRIVATE_KEY }}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy via SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ steps.set-vars.outputs.pkey }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          HOST=$(echo "${{ steps.set-vars.outputs.server }}" | cut -d'@' -f2)
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

          scp -r smartDine-server/docker-compose.yml smartDine-server/${{ steps.set-vars.outputs.envfile }} ${{ steps.set-vars.outputs.server }}:~/app

          ssh ${{ steps.set-vars.outputs.server }} << 'EOSSH'
            cd ~/app
            docker-compose down
            docker-compose pull
            docker-compose up -d --build
            docker-compose exec laravel php artisan migrate --force
            docker-compose exec laravel php artisan optimize:clear
          EOSSH
