name: Deploy SmartDine App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Laravel image
        uses: docker/build-push-action@v4
        with:
          context: ./smartDine-server
          push: true
          tags: yehiaarja/dockersmartdine:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PRODUCTION_SERVER }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.PRODUCTION_EC2_KEY }}
          script: |
            # Install Docker
            if ! command -v docker &> /dev/null; then
              sudo apt update && sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
            fi

            # Install Docker Compose
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Clone latest repo (if needed)
            mkdir -p ~/smartdine && cd ~/smartdine
            curl -o docker-compose.yml https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yml

            echo "Pulling latest Laravel image..."
            docker pull yehiaarja/dockersmartdine:latest

            echo "Stopping old containers..."
            docker compose down || true

            echo "Starting new containers..."
            docker compose up -d

            echo "Waiting for DB..."
            sleep 10

            echo "Running migrations and seeders..."
            docker exec smartdine-server php artisan migrate:fresh --seed --force

            echo "Clearing Laravel cache..."
            docker exec smartdine-server php artisan optimize:clear

            echo "Container logs:"
            docker logs smartdine-server --tail 50 || true
