name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - production

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    name: Build → Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare Docker Buildx cache
        run: mkdir -p /tmp/.buildx-cache

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build & start containers
        working-directory: smartDine-server
        run: |
          docker compose build --pull
          docker compose up -d

      - name: Wait for MySQL to be healthy
        working-directory: smartDine-server
        run: |
          docker compose exec -T mysql sh -c "until mysqladmin ping -h localhost --silent; do sleep 1; done"

      - name: Run migrations
        working-directory: smartDine-server
        run: docker compose exec -T laravel php artisan migrate --force

      - name: Run tests
        working-directory: smartDine-server
        run: docker compose exec -T laravel php artisan test --verbose

  deploy-staging:
    name: Deploy to Staging EC2
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    env:
      EC2_HOST: ${{ secrets.EC2_STAGING_HOST }}
      BRANCH: main

    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_DEPLOY_KEY }}

      - name: SSH & deploy to staging
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@"${EC2_HOST}" << 'EOF'
            cd ~/Restaurant-Manager/smartDine-server
            git pull origin "${BRANCH}"
            docker compose down
            docker compose up -d --build
          EOF

  deploy-production:
    name: Deploy to Production EC2
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/production'
    env:
      EC2_HOST: ${{ secrets.EC2_PRODUCTION_HOST }}
      BRANCH: production

    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_DEPLOY_KEY }}

      - name: SSH & deploy to production
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@"${EC2_HOST}" << 'EOF'
            cd ~/Restaurant-Manager/smartDine-server
            git pull origin "${BRANCH}"
            docker compose down
            docker compose up -d --build
          EOF
