name: CI/CD Pipeline

on:
  push:
    branches: [main, production]

env:
  DOCKER_COMPOSE_VERSION: "3.8"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Install Docker-Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build containers
        working-directory: smartDine-server
        run: docker-compose -f docker-compose.yml build

  test:
    needs: build
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports: ["3306:3306"]
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, xml, ctype, json, tokenizer, bcmath, redis, pdo_mysql

      - name: Install dependencies
        working-directory: smartDine-server
        run: composer install --no-interaction --prefer-dist

      - name: Prepare .env
        working-directory: smartDine-server
        run: |
          cp .env.example .env
          printf '%s\n' \
            "APP_ENV=testing" \
            "DB_HOST=127.0.0.1" \
            "DB_DATABASE=test_db" \
            "DB_USERNAME=root" \
            "DB_PASSWORD=root" >> .env

      - name: Run PHPUnit
        working-directory: smartDine-server
        run: |
          php artisan key:generate --env=testing
          php artisan migrate:fresh --env=testing
          php artisan test

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production'

    steps:
      - uses: actions/checkout@v4

      - id: prep
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "server=${{ secrets.STAGING_SERVER }}"       >> $GITHUB_OUTPUT
            echo "${{ secrets.SSH_STAGING_PRIVATE_KEY }}"      >  private_key.pem
            echo "envfile=.env.staging"                       >> $GITHUB_OUTPUT
          else
            echo "server=${{ secrets.PRODUCTION_SERVER }}"    >> $GITHUB_OUTPUT
            echo "${{ secrets.SSH_PRODUCTION_PRIVATE_KEY }}"   >  private_key.pem
            echo "envfile=.env.production"                    >> $GITHUB_OUTPUT
          fi

      - name: Deploy via SSH
        env:
          SERVER: ${{ steps.prep.outputs.server }}
          ENVFILE: ${{ steps.prep.outputs.envfile }}
        run: |
          mkdir -p ~/.ssh
          cp private_key.pem ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          HOST=$(printf '%s' "$SERVER" | cut -d'@' -f2)
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

          scp -r smartDine-server/docker-compose.yml smartDine-server/$ENVFILE "$SERVER":/app

          ssh "$SERVER" <<'EOSSH'
            cd /app
            docker-compose down
            docker-compose pull
            docker-compose up -d --build
            docker-compose exec laravel php artisan migrate --force
            docker-compose exec laravel php artisan optimize:clear
          EOSSH
