name: Push and Run

on:
  push:
    branches:
      - main
      - production

jobs:
  Build-Test-Push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./smartDine-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Laravel image
        run: docker build -t yehiaarja/dockersmartdine:latest .

      - name: Start services
        run: docker compose up -d --wait

      - name: Wait for DB to be ready
        run: |
          echo "Waiting for DB to be ready..."
          MAX_RETRIES=30
          RETRY_INTERVAL=2
          COUNT=0

          until docker exec smartdine-server-database-1 sh -c 'mysqladmin ping -uroot -p1234 --silent'; do
            COUNT=$((COUNT+1))
            if [ $COUNT -ge $MAX_RETRIES ]; then
              echo "DB did not become ready in time"
              exit 1
            fi
            echo "Still waiting... ($COUNT)"
            sleep $RETRY_INTERVAL
          done
          echo "DB is ready!"

      - name: Run migrations
        run: docker compose exec server php artisan migrate --force

      - name: Run tests
        run: docker compose exec server php artisan test

      - name: Push Laravel Docker image
        run: docker push yehiaarja/dockersmartdine:latest
